/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.groupc.ers;


import java.awt.CardLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author micheal
 */
public class homepage extends javax.swing.JFrame {



    // Constructor
    public homepage() {
        initComponents();
        
         mainJPanel.setLayout(new java.awt.CardLayout()); // Set CardLayout AFTER initComponent
         mainJPanel.add(ViewAllCard, "ViewAllCard");
         mainJPanel.add(jNewReg, "jNewReg");
         
         this.setLocationRelativeTo(null);

        setupTable();         // Step 1: Set column headers
        loadStudentData();    // Step 2: Load data into table
    }

    // Method to show the "ViewAllCard" panel in mainJPanel
   
    
    public void showViewAllCard() {
        CardLayout cl = (CardLayout) mainJPanel.getLayout();
        cl.show(mainJPanel, "ViewAllCard");
    }
    
    public void showjNewRegCard() {
        CardLayout cl = (CardLayout) mainJPanel.getLayout();
        cl.show(mainJPanel, "jNewReg");
    }
    
    

    // Step 1: Set column headers
    private void setupTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setColumnIdentifiers(new String[]{
            "Registration ID", "Student Name", "Faculty", "Project Title",
            "Contact Number", "Email Address", "Project Prototype"
        });
    }

    // Step 2: Load student records from the database
    private void loadStudentData() {
        recordsDAO dao = new recordsDAO();
        List<Student> students = dao.getAllRecords();

        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0); // Clear previous data

        for (Student s : students) {
            model.addRow(new Object[]{
                s.getRegistrationId(),
                s.getStudentName(),
                s.getFaculty(),
                s.getProjectTitle(),
                s.getContactNumber(),
                s.getEmailAddress(),
                s.getProjectPrototype()
            });
        }
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newImageChooser = new javax.swing.JFileChooser();
        jSidePanel = new javax.swing.JPanel();
        jBtnRegister = new javax.swing.JButton();
        jBtnRecords = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        mainJPanel = new javax.swing.JPanel();
        jNewReg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newTextRegID = new javax.swing.JTextField();
        newTextFaculty = new javax.swing.JTextField();
        newTextName = new javax.swing.JTextField();
        newContactNo = new javax.swing.JTextField();
        newProject = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        jBtnChooseImage = new javax.swing.JButton();
        jBtnAddStd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        ViewAllCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnRegister.setText("Register");
        jBtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegisterActionPerformed(evt);
            }
        });

        jBtnRecords.setText("Registered  Students");
        jBtnRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRecordsActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jBtnEdit.setText("Edit");
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSidePanelLayout = new javax.swing.GroupLayout(jSidePanel);
        jSidePanel.setLayout(jSidePanelLayout);
        jSidePanelLayout.setHorizontalGroup(
            jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSidePanelLayout.createSequentialGroup()
                .addGroup(jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jBtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jSidePanelLayout.setVerticalGroup(
            jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSidePanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jBtnRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        mainJPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainJPanel.setLayout(new java.awt.CardLayout());

        jNewReg.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Registration ID: ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Contact Number: ");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Project Title: ");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Email Address: ");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Name: ");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Faculty: ");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Image of Prototype: ");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Add New Student");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fill in the details blow to register a new student");

        newEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailActionPerformed(evt);
            }
        });

        jBtnChooseImage.setText("Select  Image");
        jBtnChooseImage.setBorderPainted(false);
        jBtnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChooseImageActionPerformed(evt);
            }
        });

        jBtnAddStd.setText("Add");
        jBtnAddStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddStdActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Save");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNewRegLayout = new javax.swing.GroupLayout(jNewReg);
        jNewReg.setLayout(jNewRegLayout);
        jNewRegLayout.setHorizontalGroup(
            jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewRegLayout.createSequentialGroup()
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jNewRegLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jNewRegLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jNewRegLayout.createSequentialGroup()
                            .addGap(309, 309, 309)
                            .addComponent(jBtnAddStd)
                            .addGap(42, 42, 42)
                            .addComponent(jBtnUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                            .addComponent(jButton3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jNewRegLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jNewRegLayout.createSequentialGroup()
                                    .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2))
                                    .addGap(41, 41, 41)
                                    .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newTextFaculty)
                                        .addComponent(newTextName)
                                        .addComponent(newTextRegID)))
                                .addGroup(jNewRegLayout.createSequentialGroup()
                                    .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jBtnChooseImage)
                                        .addComponent(newEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                                        .addComponent(newContactNo)
                                        .addComponent(newProject)))))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jNewRegLayout.setVerticalGroup(
            jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewRegLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNewRegLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNewRegLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newTextRegID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newTextFaculty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jBtnChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jNewRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddStd)
                    .addComponent(jButton3)
                    .addComponent(jBtnUpdate))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        mainJPanel.add(jNewReg, "newRegCard");

        ViewAllCard.setBackground(new java.awt.Color(244, 244, 245));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("All Registered Students");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        javax.swing.GroupLayout ViewAllCardLayout = new javax.swing.GroupLayout(ViewAllCard);
        ViewAllCard.setLayout(ViewAllCardLayout);
        ViewAllCardLayout.setHorizontalGroup(
            ViewAllCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllCardLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
            .addGroup(ViewAllCardLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addGap(97, 97, 97))
        );
        ViewAllCardLayout.setVerticalGroup(
            ViewAllCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllCardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        mainJPanel.add(ViewAllCard, "viewAllCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegisterActionPerformed
        // TODO add your handling code here:
   
        CardLayout cl = (CardLayout) mainJPanel.getLayout();
        cl.show(mainJPanel, "jNewReg");   
    }//GEN-LAST:event_jBtnRegisterActionPerformed

    private void newEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmailActionPerformed

    private void jBtnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChooseImageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();

    // Filter only image files (optional but recommended)
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Image files", "jpg", "jpeg", "png", "gif", "bmp"));

    int result;
    result = fileChooser.showOpenDialog(jLabel1);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = fileChooser.getSelectedFile();
        String imagePath = selectedFile.getAbsolutePath();
        
        // For now, just show the path (you can use it to display or upload the image)
        JOptionPane.showMessageDialog(this, "Selected Image: " + imagePath);
        
        // Example: Load image into a JLabel (optional)
        // ImageIcon imageIcon = new ImageIcon(imagePath);
        // myImageLabel.setIcon(imageIcon);
    }
        
    }//GEN-LAST:event_jBtnChooseImageActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
       
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to logout?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Close the current window
        this.dispose();

        // Open the login form
        new Login().setVisible(true);
    }
    }//GEN-LAST:event_logoutActionPerformed

    private void jBtnRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRecordsActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainJPanel.getLayout();
        cl.show(mainJPanel, "ViewAllCard");
    }//GEN-LAST:event_jBtnRecordsActionPerformed

    private void jBtnAddStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddStdActionPerformed
        // TODO add your handling code here:
        String regId = newTextRegID.getText();
    String name = newTextName.getText();
    String faculty = newTextFaculty.getText();
    String project = newProject.getText();
    String contact = newContactNo.getText();
    String email = newEmail.getText();
    String prototype = "N/A"; // You can change this to actual image filename later

    // Simple validation
    if (regId.isEmpty() || name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in required fields.");
        return;
    }

    // Add row to table
    DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
    model.addRow(new Object[]{regId, name, faculty, project, contact, email, prototype});

    // Optional: Clear fields after adding
    newTextRegID.setText("");
    newTextName.setText("");
    newTextFaculty.setText("");
    newProject.setText("");
    newContactNo.setText("");
    newEmail.setText("");

    // Optional: Switch to ViewAllCard to see the result
    CardLayout cl = (CardLayout) mainJPanel.getLayout();
    cl.show(mainJPanel, "ViewAllCard");

        
    }//GEN-LAST:event_jBtnAddStdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
   
    CardLayout cl = (CardLayout) mainJPanel.getLayout();
    cl.show(mainJPanel, "ViewAllCard");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudents.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to edit.");
        return;
    }

    // Load data into form fields
    newTextRegID.setText(tblStudents.getValueAt(selectedRow, 0).toString());
    newTextName.setText(tblStudents.getValueAt(selectedRow, 1).toString());
    newTextFaculty.setText(tblStudents.getValueAt(selectedRow, 2).toString());
    newProject.setText(tblStudents.getValueAt(selectedRow, 3).toString());
    newContactNo.setText(tblStudents.getValueAt(selectedRow, 4).toString());
    newEmail.setText(tblStudents.getValueAt(selectedRow, 5).toString());

    // Switch to the registration panel
    showjNewRegCard();

       
    }//GEN-LAST:event_jBtnEditActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblStudents.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a record to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    String regId = tblStudents.getValueAt(selectedRow, 0).toString();

    // Remove from DB
    recordsDAO dao = new recordsDAO();
    dao.deleteRecord(regId);

    // Remove from table
    DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
    model.removeRow(selectedRow);

    JOptionPane.showMessageDialog(this, "Student deleted.");
        
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        
        String regId = newTextRegID.getText();
        String name = newTextName.getText();

        String faculty = newTextFaculty.getText();
        String project = newProject.getText();
        String contact = newContactNo.getText();
        String email = newEmail.getText();
        String prototype = ""; // Optional

    recordsDAO dao = new recordsDAO();
    boolean success = dao.updateRecord(regId, name, faculty, project, contact, email, prototype);

    if (success) {
        JOptionPane.showMessageDialog(this, "Student updated.");
        loadStudentData();
        showViewAllCard();
    } else {
        JOptionPane.showMessageDialog(this, "Update failed.");
    }
        
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewAllCard;
    private javax.swing.JButton jBtnAddStd;
    private javax.swing.JButton jBtnChooseImage;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jBtnRecords;
    private javax.swing.JButton jBtnRegister;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jNewReg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jSidePanel;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JTextField newContactNo;
    private javax.swing.JTextField newEmail;
    private javax.swing.JFileChooser newImageChooser;
    private javax.swing.JTextField newProject;
    private javax.swing.JTextField newTextFaculty;
    private javax.swing.JTextField newTextName;
    private javax.swing.JTextField newTextRegID;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables

    
}